version: '3'
services:
    #PHP Service
    app:
        image: devilbox/php-fpm:8.1-work
        container_name: app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: always
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
    #MySQL Service
    db:
        image: mariadb:10.3
        container_name: db
        restart: always

        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 331
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        networks:
            - app-network
 #   redis:
 #       image: redis:latest
 #       container_name: laravel_cache
 #       restart: always
 #       ports:
 #           - "6379:6379"
 #       volumes:
 #           - ./cache_data_redis:/data
 #       networks:
 #           - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local